// Auto-generated by make — do not edit
let buildVersion = "0.6.24"
let buildCommit = "efe344d"
let buildBranch = "main"
let buildDate = "2026-04-03 13:25:51 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
