// Auto-generated by make — do not edit
let buildVersion = "0.6.27"
let buildCommit = "07c579b"
let buildBranch = "main"
let buildDate = "2026-04-03 19:39:58 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
