// Auto-generated by make — do not edit
let buildVersion = "0.6.30"
let buildCommit = "a7b8424"
let buildBranch = "main"
let buildDate = "2026-04-03 21:17:36 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
